name: Solidity Tests

on:
  push:
    branches:
      - dev

defaults:
  run:
    working-directory: ./bridging-block

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SEPOLIA_PRIVATE_KEY: ${{ secrets.SEPOLIA_PRIVATE_KEY }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.20"

      - name: Install dependencies
        run: npm install

      - name: Compile the contract
        run: npx hardhat compile

      - name: Run tests
        run: npx hardhat test
